default:
    servers:
       app:
          port:3000
    log:
       app:
          filename: /var/log/node/app
          level: debug
          colorize: true
          datePattern: -yyyy-MM-dd
          json: false

local:

test: 

development:

production:
