default:
    servers:
       application:
          port: 4000
    log:
       application:
          filename: /var/log/node/application
          level: debug
          colorize: true
          datePattern: -yyyy-MM-dd
          json: false

    mongo:
        servers:
            server1:
                host: localhost
                port: 27017
            server2:
                host: localhost
                port: 27018
        database: app
        options:
            replSet: test
            connectTimeoutMS: 5000
            socketTimeoutMS: 5000
            maxPoolSize: 25

local:

test: 

development:

production:
